glamhubsite/appointments/urls.py
from django.urls import path

from . import views

app_name = 'appointments'
urlpatterns = [
    path('<str:slug>/create/', views.AppointmentCreateView.as_view(), name='create'), # noqa
    path('<str:slug>/list/', views.list_appointments, name='list'), # noqa
    path('<int:pk>/approve/', views.approve_appointment, name='approve'), # noqa
    path('<int:pk>/reject/', views.reject_appointment, name='reject'), # noqa




]

glamhubsite/artist/urls.py
from django.urls import path
from artist.views import (
    create_artistportfolio_view,
    detail_artistportfolio_view,
    edit_artistportfolio_view,
)

app_name = 'artist'

urlpatterns = [
    path('create/', create_artistportfolio_view, name="create"),
    path('<slug>/', detail_artistportfolio_view, name="detail"),
    path('<slug>/edit/', edit_artistportfolio_view, name="edit"),
]

glamhubsite/blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    comment_approve,
    comment_remove,
    add_comment_to_post,
)
# from personal.view import SearchResultsView

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
    path('posts/<int:pk>/comment/', add_comment_to_post, name='add_comment'), # noqa
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    # path('search/', SearchResultsView.as_view(), name='search_results'),
]

glamhubsite/glamhubsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

# from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views

from personal.views import (
    home_screen_view,
    about_us_view,
    blog_posts_view,
    artist_portfolio_screen,
    contact_us_view,
    services_screen_view,


    )

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)


from appointments.views import approve_appointment, reject_appointment

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('about/', about_us_view, name="about"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'), # noqa
    path('ckeditor/browser/', never_cache(login_required(views.browse)), name='ckeditor_browse'), # noqa
    path('posts/', blog_posts_view, name="post"),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),  # noqa
    path('register/', registration_view, name="register"),
    path('artist/', include('artist.urls', 'artist')),  # noqa
    path('artist_portfolios/', artist_portfolio_screen, name="artist_portfolios"), # noqa
    path('contact_us/', contact_us_view, name="contact_us"),
    path('services/', services_screen_view, name="services"),
    path('appointments/', include('appointments.urls')),
    path('reviews/', include('review.urls', 'reviews')),





    #  Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path(
        'password_reset/', auth_views.PasswordResetView.as_view(),
        name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),



    path(
        'appointment_approval/', approve_appointment),
    path(
        'appointment_reject/', reject_appointment),



]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # noqa
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # noqa

glamhubsite/review/urls.py
from django.urls import path
from artist.views import add_review_to_portfolio, detail_artistportfolio_view

# from personal.view import SearchResultsView

app_name = 'review'

urlpatterns = [
    path('reviews/<int:pk>/review/', add_review_to_portfolio, name='add_review'), # noqa
    path('artist/<slug>/', detail_artistportfolio_view, name="detail"),
]

glamhubsite/artist/models.py
from django.db import models
from phone_field import PhoneField

from django.utils.text import slugify
from django.conf import settings
# from django.db.models.signals import post_delete
# from django.dispatch import receiver

# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

from account.models import Account


# method to define the upload location for images associated with blog posts
def upload_location(instance, filename, **kwargs):
    file_path = 'artist/{business_owner_id}/{business_name}-{filename}'.format(
            business_owner_id=str(instance.business_owner.id),
            business_name=str(instance.business_owner),
            filename=filename
        )
    return file_path

# define a constant (tuple choices to keep status of the business.)
STATUS = [ # noqa
    ('A', 'Active'),
    ('I', 'Inactive'),
]


class ArtistryCategory(models.Model):
    name = models.CharField(max_length=200)
    description = RichTextUploadingField(max_length=1000, blank=True, null=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class ArtistPortfolio(models.Model):
    artistry_category = models.ForeignKey(ArtistryCategory, on_delete=models.CASCADE)
    business_name = models.CharField(max_length=200)
    business_owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # noqa
    profile_image = models.ImageField(upload_to='pics')
    email_address = models.EmailField(max_length=70, blank=True, null=True)
    phone_number = PhoneField(null=False, blank=False)
    description = RichTextUploadingField(max_length=10000, blank=True, null=True) # noqa
    portfolio_images = RichTextUploadingField(max_length=10000, blank=True, null=True, config_name='special', external_plugin_resources=[('youtube', '/static/personal/vendor/ckeditor_plugins/youtube', 'plugin.js',)],) # noqa
    slug = models.SlugField(max_length=255, blank=True, null=True, unique=True)
    status = models.CharField(max_length=1, choices=STATUS)

    class Meta:
        verbose_name = "Artist Portfolio"
        verbose_name_plural = "Artist Porfolios"
        ordering = ['business_owner', 'business_name']

    # methods
    def __str__(self):
        return self.business_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.business_name + "-" + self.business_owner.username) # noqa
        super().save(*args, **kwargs)

glamhubsite/artist/forms.py
from ckeditor.widgets import CKEditorWidget

from django import forms

from artist.models import ArtistPortfolio, ArtistryCategory
from review.models import Review
# from personal.models import ContactUs


# create artistportfolio form
class CreateArtistPortfolioForm(forms.ModelForm):
    artistry_category = forms.ModelChoiceField(
        queryset=ArtistryCategory.objects.filter(active=True),
        required=False
    )

    class Meta:
        model = ArtistPortfolio
        fields = '__all__'
        exclude = ('slug', 'business_owner')


class UpdateArtistPortfolioForm(forms.ModelForm):
    artistry_category = forms.ModelChoiceField(
        queryset=ArtistryCategory.objects.filter(active=True),
        required=False
    )

    class Meta:
        model = ArtistPortfolio
        fields = '__all__'
        exclude = ('slug', 'business_owner')

    # custom edit and save method of existing profile
    def save(self, commit=True):
        artistportfolio = self.instance
        artistportfolio.artistry_category = self.cleaned_data['artistry_category']  # noqa
        artistportfolio.business_name = self.cleaned_data['business_name']
        artistportfolio.email_address = self.cleaned_data['email_address']
        artistportfolio.phone_number = self.cleaned_data['phone_number']
        artistportfolio.description = self.cleaned_data['description']

        # if there is a new image set it
        if self.cleaned_data['profile_image']:
            artistportfolio.profile_image = self.cleaned_data['profile_image']

        if commit:
            artistportfolio.save()
        return artistportfolio


class ReviewForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        max_length=1000,
        widget=forms.TextInput(attrs={'placeholder': 'Leave a review'}),
        label=False)

    class Meta:
        model = Review
        fields = ('body',)

    

glamhubsite/artist/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.urls import reverse_lazy
# from django.http import HttpResponse

from artist.models import ArtistPortfolio
from artist.forms import CreateArtistPortfolioForm, UpdateArtistPortfolioForm
from review.models import Review
from review.forms import ReviewForm
# from account.models import Account


@login_required()
def create_artistportfolio_view(request):
    context = {}

    form = CreateArtistPortfolioForm(request.POST or None, request.FILES or None)  # noqa
    if form.is_valid():
        obj = form.save(commit=False)
        obj.business_owner = request.user
        obj.save()
        context['success_message'] = "Portfolio Created Successfully"

        form = CreateArtistPortfolioForm()

    context['artistportfolio'] = form

    return render(request, 'artist/create_artistportfolio.html', context)


@login_required()
def detail_artistportfolio_view(request, slug):

    context = {}
    artistportfolio = get_object_or_404(ArtistPortfolio, slug=slug)
    context['artistportfolio'] = artistportfolio

    return render(request, 'artist/detail_artistportfolio.html', context)


@login_required()
def edit_artistportfolio_view(request, slug):

    context = {}

    artistportfolio = get_object_or_404(ArtistPortfolio, slug=slug)
    if request.POST:
        form = UpdateArtistPortfolioForm(
            request.POST or None,
            request.FILES or None,
            instance=artistportfolio
        )

        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Updated Successfully"
            artistportfolio = obj

    form = UpdateArtistPortfolioForm(
        initial={
            "artistry_category": artistportfolio.artistry_category,
            "business_name": artistportfolio.business_name,
            "business_owner": artistportfolio.business_owner,
            "profile_image": artistportfolio.profile_image,
            "email_address": artistportfolio.email_address,
            "phone_number": artistportfolio.phone_number,
            "description": artistportfolio.description,
            "portfolio_images": artistportfolio.portfolio_images,
            "status": artistportfolio.status,

        }
    )

    context['artistportfolioform'] = form

    return render(request, 'artist/edit_artistportfolio.html', context)

    artistportfolio = get_object_or_404(ArtistPortfolio, slug=slug)
    context['artistportfolioform'] = form

    return render(request, 'artist/edit_artistportfolio.html', context)


@login_required()
def add_review_to_portfolio(request, pk):
    portfolio = get_object_or_404(ArtistPortfolio, pk=pk)
    if request.POST:
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.portfolio = portfolio
            review.name = request.user
            review.save()

            messages.success(request, "Review created successfully ")
            url = reverse_lazy('artist:detail', kwargs={
                               'slug': portfolio.slug})
            return redirect(url)

    form = ReviewForm(
        initial={
            'portfolio': portfolio
        }
    )
    return render(request, 'reviews/add_review.html', {'form': form})


# method to get a queryset based on a particular search
def get_artistportfolios_queryset(query=None):
    queryset = []
    queries = query.split(" ")  # how to clean would be [how, to, clean]
    for q in queries:
        portfolios = ArtistPortfolio.objects.filter(
            Q(business_name__icontains=q) |
            Q(description__icontains=q)
        ).distinct()

        for portfolio in portfolios:
            queryset.append(portfolio)

    # create unique set and then convert to list
    return list(set(queryset))

glamhubsite/artist/templates/artist/artistportfolio_pagination.html
<!-- FILTERED Pagination -->
<div class="d-flex flex-column m-auto pagination mt-5">
    <nav aria-label="Page navigation">
    <ul class="pagination pg-grey justify-content-center">
        {% if artistportfolios.has_previous %}
            <li class="page-item">
              <a class="page-link"
              href="?{% if query %}q={{query}}&{% endif %}page={{ artistportfolios.previous_page_number }}">
              &laquo; Previous</a>
            </li>
        {% endif %}

        {% for i in artistportfolios.paginator.page_range %}
            {% if artistportfolios.number == i %}
                <li class="page-item active"><a class="page-link">{{ i }}</a></li>
            {% else %}
                <li class="page-item" ><a class="page-link"
                    href="?{% if query %}q={{query}}&{% endif %}page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}

        {% if artistportfolios.has_next %}
            <li class="page-item">
              <a class="page-link"
              href="?{% if query %}q={{query}}&{% endif %}page={{ artistportfolios.next_page_number }}">
              Next</a>
            </li>
            <li class="page-item">
              <a class="page-link"
              href="?{% if query %}q={{query}}&{% endif %}page={{ artistportfolios.paginator.num_pages }}">
              Last &raquo;</a>
            </li>
        {% endif %}
    </ul>
    </nav>
    </div>
    <!-- end pagination-->

glamhubsite/artist/templates/artist/artistportfolio_snippet.html
{% load static %}
<style type="text/css">
	.card {
		max-width: 700px;
		width: 120%;
	}

	.card-body {
		padding: 20px;
	}
	.card-business_name{
		padding: 20px;
	}
	img {

		display: block;
		margin-left: auto;
		margin-right: auto;
		float: left;
		width: 100px;
		height: 300px;
		object-fit: cover;
	}

	h4 {
		font-family: 'Times New Roman', Times, serif;
	}
	p {
        font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
		text-align: justify;
	}
	.btn {
        border-radius: 2px;
        color: #343b40;
        border-color: #343b40;
        background: rgb(16, 245, 233);
        ;
        outline: none;
    }

    .btn:hover,
    .btn:focus {
        border-color: rgb(16, 245, 233);
        ;
        background-color: #343b40;
        color: rgb(16, 245, 233);
        ;
    }
</style>

{% if artistportfolio %}
<div class="container">
	<div class="row">

		<!-- Artist Portfolio -->
		<div class="card m-auto">
			<a href="{% url 'artist:detail' artistportfolio.slug %}">
				{% if artistportfolio.profile_image %}
				<img class="card-img-top" src="{{artistportfolio.profile_image.url}}" alt="image missing">
				{% endif %}
			</a>
			<div class="card-body mt-2 mb-2">
				<a href="{% url 'artist:detail' artistportfolio.slug %}">
					<h4 class="card-business_name">{{artistportfolio.business_name}}</h4>
				</a>




				<p class="card-text">{{artistportfolio.description|safe|truncatechars:180}}</p>
				{% if artistportfolio.business_owner == request.user %}
				<a href="{% url 'artist:edit' artistportfolio.slug %}" class="btn ">Update</a>
				{% endif %}





			</div>
			<div class="card-footer text-muted" style="text-align: center;">
				Reviews: <a href="{% url 'artist:detail' artistportfolio.slug %}">{{ portfolio.reviews.count }}</a>
				<br>
				Owned by {{artistportfolio.business_owner|title}}

			</div>
		</div>
	</div>
</div>

{% else %}

<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-business_name" style="text-align: center; font-family: 'Times New Roman', Times, serif;">Nothing Found</h2>
				<p class="card-text"  style="text-align: center; font-family: 'Times New Roman', Times, serif;">There were no results matching the search</p>
			</div>
		</div>
	</div>
</div>

{% endif %}

glamhubsite/artist/templates/artist/create_artistportfolio.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{ artistportfolio | crispy }}
				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">CREATE</button>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

glamhubsite/artist/templates/artist/detail_artistportfolio.html
{% extends 'base.html' %}

<!-- {% load crispy_forms_tags %} -->

{% block content %}

<style type="text/css">
    .card {
        max-width: 700px;
    }


    .container {
        padding: 20px;
    }

    img {

        display: block;
        margin-left: auto;
        margin-right: auto;
        float: left;
        width: 100%;
        height: 300px;
        object-fit: cover;
    }

    h4 {
        font-family: 'Times New Roman', Times, serif;
        text-align: center;
    }

    p {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        text-align: justify;
    }
    .btn {
        border-radius: 2px;
        color: #343b40;
        border-color: #343b40;
        background: rgb(16, 245, 233);
        ;
        outline: none;
    }

    .btn:hover,
    .btn:focus {
        border-color: rgb(16, 245, 233);
        ;
        background-color: #343b40;
        color: rgb(16, 245, 233);
        ;
    }
    .card-white .h5 {
        font-size: 14px;
        //font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;

    }

    .card-white .time {
        font-size: 12px;
        //font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    }

    .post .post-heading {
        height: 95px;
        padding: 20px 15px;
    }

    post .post-heading .meta .time {
        margin-top: 8px;
        color: #999;
    }

    .post .post-description {
        padding: 15px;
    }

    .post .post-description p {
        font-size: 14px;
    }

    .widget-area {
        background-color: #fff;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        -ms-border-radius: 4px;
        -o-border-radius: 4px;
        border-radius: 4px;
        -webkit-box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        -moz-box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        -ms-box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        -o-box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        float: left;
        margin-top: 30px;
        padding: 25px 30px;
        position: relative;
        width: 100%;
    }
</style>

<div class="container">
    <div class="row">
        <!-- Artist Portfolio -->
        <div class="card m-auto">
            {% if artistportfolio.profile_image %}
            <img class="card-body-top" src="{{artistportfolio.profile_image.url}}">
            {% endif %}
            <div class="card-body my-2">
                <h4 class="card-business_name">{{artistportfolio.business_name}}</h4>
                <p class="card-text">{{artistportfolio.description|safe}}</p>
                <hr>
                <p class="card-text">{{artistportfolio.portfolio_images|safe}}</p>
            </div>
            <div class="card-body my-2" style=" text-align:center">
                {% if  artistportfolio.business_owner == request.user %}
                <a href="{% url 'artist:edit' artistportfolio.slug %}" class="btn btn-primary">Update</a>                {% endif %}

            </div>
            <div class="card-body my-2" style=" text-align:center">
                {% if  artistportfolio.business_owner == request.user %}
                <a href="{%url 'appointments:list' artistportfolio.slug %}" class="btn -primary">Check your Appointments</a>
                {% elif not request.user.is_artist %}
                <a href="{%url 'appointments:create' artistportfolio.slug %}" class="btn btn-primary">Book an Appointment</a>
                {% endif %}
            </div>


            <div class="card-footer text-muted" style="text-align: right;">
                Owned by {{artistportfolio.business_owner|title}}
            </div>
            <div class="col-md-8 card mb-4  mt-3 " style="max-width: -50%; align-items: center; text-align: center; background:rgb(241, 241, 241);">
                <!-- reviews section -->
                <!-- <form action="{% url 'review:add_review' artistportfolio.pk %}" method="POST" class="post-form">{% csrf_token %}
                    {{ form | crispy }}
                    <button type="submit" class="btn btn-default">Add review</button>
                </form> -->
                <!-- <div class="widget-area no-padding blank">
                    <a href="{% url 'review:add_review' artistportfolio.pk %}" class="btn btn-primary">Add a review</a>
                </div> -->

                <div class="col-md-8 card mb-4  mt-3 ">
                    <!-- reviews section -->
                    <div class="widget-area no-padding blank">
                        <form action="{% url 'review:add_review' artistportfolio.pk %}" method="POST" class="post-form">{% csrf_token %}
                            {{ form | crispy }}
                            <button type="submit" class="btn btn-default">Add review</button>
                        </form>
                    </div>
                    <!--

                        <button type="submit" class="btn btn-default">Add review</button>
                    -->


                    <br>
                <br>
                {% for review in artistportfolio.reviews.all %}
                {% if user.is_authenticated %}
                <div class="container">
                <div class="row">
                    <div class="col-8">
                        <div class="card card-white post ">

                            <div class="post-heading">

                                <div class="float-center meta">

                                    <div class="title h5">
                                        <h8>{{ review.name.username}} left a review</h8>
                                    </div>
                                        <h6 class="text-muted time">{{ review.created_on }}</h6>
                                    </div>
                                    <div>
                                        <p>{{ review.body |capfirst | linebreaks }}</p>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>

                    {% endif %}

                    {% empty %}
                    <hr>
                    <p></p>No reviews here yet :(</p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- End Blog Post -->

    </div>
</div>
{% endblock content %}

glamhubsite/artist/templates/artist/edit_artistportfolio.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color: green; text-align: center;">{{success_message}}</h3>
			{% endif%}
			<form class="create-form" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{ artistportfolioform.media }}
				{{ artistportfolioform | crispy }}
				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit"
				>Update</button>
			</form>
		</div>
	</div>
</div>

{% endblock content %}