glamhubsite/blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    comment_approve,
    comment_remove,
    add_comment_to_post,
)
# from personal.view import SearchResultsView

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
    path('posts/<int:pk>/comment/', add_comment_to_post, name='add_comment'), # noqa
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    # path('search/', SearchResultsView.as_view(), name='search_results'),
]

glamhubsite/glamhubsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

# from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views

from personal.views import (
    home_screen_view,
    about_us_view,
    blog_posts_view,
    artist_portfolio_screen,
    contact_us_view,
    services_screen_view,


    )

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)


from appointments.views import approve_appointment, reject_appointment

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('about/', about_us_view, name="about"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'), # noqa
    path('ckeditor/browser/', never_cache(login_required(views.browse)), name='ckeditor_browse'), # noqa
    path('posts/', blog_posts_view, name="post"),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),  # noqa
    path('register/', registration_view, name="register"),
    path('artist/', include('artist.urls', 'artist')),  # noqa
    path('artist_portfolios/', artist_portfolio_screen, name="artist_portfolios"), # noqa
    path('contact_us/', contact_us_view, name="contact_us"),
    path('services/', services_screen_view, name="services"),
    path('appointments/', include('appointments.urls')),
    path('reviews/', include('review.urls', 'reviews')),





    #  Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path(
        'password_reset/', auth_views.PasswordResetView.as_view(),
        name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),



    path(
        'appointment_approval/', approve_appointment),
    path(
        'appointment_reject/', reject_appointment),



]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # noqa
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # noqa

glamhubsite/blog/models.py
from django.db import models

from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver

# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

from account.models import Account


# method to define the upload location for images associated with blog posts
def upload_location(instance, filename, **kwargs):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
            author_id=str(instance.author.id),
            title=str(instance.title),
            filename=filename
        )
    return file_path


class BlogPost(models.Model):
    title = models.CharField(max_length=255, null=False, blank=False)
    body = RichTextUploadingField(max_length=50000, null=False, blank=False)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True)
    date_published = models.DateTimeField(auto_now_add=True, verbose_name="date published")  # noqa
    date_updated = models.DateTimeField(auto_now=True, verbose_name="date updated")  # noqa
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # noqa
    slug = models.SlugField(max_length=255, blank=True, null=True, unique=True)

    # to return title when referenced
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.author.username + "-" + self.title)
        super().save(*args, **kwargs)


# to delete images associated with a blog post that is deleted
@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)


class Comment(models.Model):
    post = models.ForeignKey('blog.BlogPost', on_delete=models.CASCADE, related_name='comments') # noqa
    participant = models.ForeignKey(
        Account, on_delete=models.CASCADE,
        blank=True, null=True)
    body = models.TextField(help_text='Your comment')
    created_on = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on', 'participant']

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.participant_name)

glamhubsite/blog/forms.py
# from ckeditor.widgets import CKEditorWidget

from django import forms
# from django.forms import ModelForm

from blog.models import BlogPost, Comment


# create blogpost form
class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']


class UpdateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

    # custom edit and save method of existing post
    def save(self, commit=True):
        blog_post = self.instance
        blog_post.title = self.cleaned_data['title']
        blog_post.body = self.cleaned_data['body']

        # if there is a new image set it
        if self.cleaned_data['image']:
            blog_post.image = self.cleaned_data['image']

        if commit:
            blog_post.save()
        return blog_post


class CommentForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        max_length=1000,
        widget=forms.TextInput(attrs={'placeholder': 'Enter comment'}),
        label=False)

    class Meta:
        model = Comment
        fields = ('body',)

glamhubsite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
# from django.http import HttpResponse
from django.urls import reverse_lazy

from blog.models import BlogPost, Comment
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm, CommentForm
# from account.models import Account


@login_required()
def create_blog_view(request):
    context = {}

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.author = request.user
        obj.save()
        context['success_message'] = "Post Created Successfully"

        form = CreateBlogPostForm()

    context['form'] = form

    return render(request, 'blog/create_blog.html', context)


@login_required()
def detail_blog_view(request, slug):

    context = {}

    blog_post = get_object_or_404(BlogPost, slug=slug)
    form = CommentForm()
    context['blog_post'] = blog_post
    context['form'] = form

    return render(request, 'blog/detail_blog.html', context)


# def add_comment_to_post(request, pk):
#     post = get_object_or_404(BlogPost, pk=pk)
#     if request.method == "POST":
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.post = post
#             comment.save()
#             return redirect('blog:detail', slug=post.slug)
#     else:
#         form = CommentForm()
#     return render(request, 'blog/add_comment_to_post.html', {'form': form})


@login_required()
def edit_blog_view(request, slug):

    context = {}

    blog_post = get_object_or_404(BlogPost, slug=slug)
    if request.POST:
        form = UpdateBlogPostForm(
            request.POST or None,
            request.FILES or None,
            instance=blog_post
        )
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            context['success_message'] = "Updated Successfully"
            blog_post = obj

    form = UpdateBlogPostForm(
        initial={
            "title": blog_post.title,
            "body": blog_post.body,
            "image": blog_post.image,
        }
    )

    context['form'] = form

    return render(request, 'blog/edit_blog.html', context)

    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['form'] = form

    return render(request, 'blog/edit_blog.html', context)


@login_required()
def add_comment_to_post(request, pk):
    post = get_object_or_404(BlogPost, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.participant = request.user
            comment.save()
            url = reverse_lazy('blog:detail', kwargs={'slug': post.slug})
            return redirect(url)
    else:
        form = CommentForm()
    return render(request, 'blog/detail_blog.html', {'form': form})


@login_required()
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog/detail_blog.html', pk=comment.post.pk)


@login_required()
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('blog/detail_blog.html', pk=comment.post.pk)


# # method to get a queryset based on a particular search
# def get_blog_queryset(query=None):
#     queryset = []
#     queries = query.split(" ")
#     for q in queries:
#         posts = BlogPost.objects.filter(
#                 Q(title__icontains=q) |
#                 Q(body__icontains=q)
#             ).distinct()
#         for post in posts:
#             queryset.append(post)

#     # create unique set and then convert to list
#     return list(set(queryset))


def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    for q in queries:
        posts = BlogPost.objects.filter(
            Q(title__contains=q) |
            Q(body__icontains=q)
        ).distinct()
        for post in posts:
            queryset.append(post)

    # create unique set and then convert to list
    return list(set(queryset))

glamhubsite/blog/templates/blog/add_comment.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<style type="text/css">
.btn {
        border-radius: 2px;
        color: #343b40;
        border-color: #343b40;
        background: rgb(16, 245, 233);
        ;
        outline: none;
    }

    .btn:hover,
    .btn:focus {
        border-color: rgb(16, 245, 233);
        ;
        background-color: #343b40;
        color: rgb(16, 245, 233);
        ;
    }
</style>
<h4>New comment</h4>
    <form action="{% url 'add_comment'  %}" method="POST" class="post-form">{% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-default">Send</button>
    </form>

glamhubsite/blog/templates/blog/create_blog.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}


<style type="text/css">
  .create-form {
	    width: 100%;
	    max-width: 100%;
	    padding: 15px;
	    margin: auto;
  	}

  	.submit-button{
  		max-width: 200px;
  	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
				<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}
			<form class="create-form" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.media }}
				{{ form | crispy }}


				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block btn-primary" type="submit">POST</button>
			</form>
		</div>
	</div>
</div>

{% endblock content %}

glamhubsite/blog/templates/blog/detail_blog.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style type="text/css">
    .card {
        max-width: 800px;
    }


    .container {
        padding: 20px;
    }

    img {

        display: block;
        margin-left: auto;
        margin-right: auto;
        float: left;
        width: 100%;
        height: 300px;
        object-fit: cover;
    }

    h4 {
        font-family: 'Times New Roman', Times, serif;
        text-align: center;
    }

    p {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        text-align: justify;
    }

    .comment {
        margin: 20px 0px 20px 20px;
    }

    .btn {
        border-radius: 2px;
        color: #343b40;
        border-color: #343b40;
        background: rgb(16, 245, 233);
        ;
        outline: none;
    }

    .btn:hover,
    .btn:focus {
        border-color: rgb(16, 245, 233);
        ;
        background-color: #343b40;
        color: rgb(16, 245, 233);
        ;
    }

    .card-white {
        text-align: center;
        align-content: center;
    }

    .card-white .h5 {
        font-size: 14px;
        //font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;

    }

    .card-white .time {
        font-size: 12px;
        //font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    }

    .post .post-heading {
        height: 95px;
        padding: 20px 15px;
    }

    post .post-heading .meta .time {
        margin-top: 8px;
        color: #999;
    }

    .post .post-description {
        padding: 15px;
    }

    .post .post-description p {
        font-size: 14px;
    }

    .widget-area {
        background-color: #fff;
        -webkit-border-radius: 4px;
        -moz-border-radius: 4px;
        -ms-border-radius: 4px;
        -o-border-radius: 4px;
        border-radius: 4px;
        -webkit-box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        -moz-box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        -ms-box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        -o-box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        box-shadow: 0 0 16px rgba(0, 0, 0, 0.05);
        float: left;
        margin-top: 30px;
        padding: 25px 30px;
        position: relative;
        width: 100%;
    }
</style>

<div class="container">
    <div class="row">
        <!-- Blog Post -->
        <div class="card m-auto">
            {% if blog_post.image %}
            <img class="card-body-top" src="{{blog_post.image.url}}">
            {% endif %}
            <div class="card-body my-2">
                <h4 class="card-title">{{blog_post.title}}</h4>
                <p class="card-text" style="text-align: justify;">{{blog_post.body|safe}}</p>


            </div>
            <div class="card-body my-2">
                {% if  blog_post.author == request.user %}
                <a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">Update</a>
                {% endif %}
            </div>
            <div class="card-footer text-muted" style="text-align: center;">
                Post by: {{blog_post.author}} Updated on {{blog_post.date_updated}}
            </div>
            <!-- End Blog Post -->
            <div class="col-md-8 card mb-4  mt-3 "
                style="max-width: -50%; align-items: center; text-align: center; background:rgb(241, 241, 241); ">
                <!-- comments section -->
                <div class="widget-area no-padding blank">

                    <form action="{% url 'blog:add_comment' blog_post.pk %}" method="POST" class="post-form"
                        style="max-width: 70%;">{% csrf_token %}
                        {{ form | crispy }}
                        <button type="submit" style="max-width: 70%; " class="btn btn-default">Add comment</button>
                    </form>
                </div>


                <br>
                {% for comment in blog_post.comments.all %}
                {% if user.is_authenticated or comment.approved_comment %}
                <div class="container">
                    <div class="row">
                        <div class="col-8">
                            <div class="card card-white post " style="white-space: nowrap;
                            overflow: hidden;
                            text-overflow: ellipsis;">

                                <div class="post-heading">

                                    <div class="float-center meta"  >

                                        <div class="title h5">
                                            <h8>{{ comment.participant.username}} commented</h8>
                                        </div>
                                        <h6 class="text-muted time">{{ comment.created_on }}</h6>
                                    </div>
                                    <div >
                                        <center>
                                            <p>{{ comment.body |capfirst |linebreaks   }}</p>
                                        </center>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>


                {% endif %}
                <hr>
                {% empty %}
                <hr>
                <p></p>No comments here yet :(</p>
                {% endfor %}
            </div>
        </div>

    </div>
    <!-- End Comments section -->
</div>
</div>
{% endblock content %}

glamhubsite/blog/templates/blog/edit_blog.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block content %}
<style type="text/css">
	.create-form {
		width: 100%;
		max-width: 100%;
		padding: 15px;
		margin: auto;
	}

	.submit-button {
		max-width: 200px;
	}

	.image {
		opacity: 1;
		transition: .5s ease;
		backface-visibility: hidden;
	}

	.middle {
		transition: .5s ease;
		opacity: 0;
		position: absolute;
		text-align: center;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);

	}

	.image-group {
		position: relative;
		text-align: center;
		cursor: pointer;
	}

	.image-group:hover .image {
		opacity: 0.3;
	}

	.image-group:hover .middle {
		opacity: 1;
	}

	.text {
		margin: auto;
		background-color: #4CAF50;
		color: white;
		font-size: 15px;
		padding: 15px;
	}
</style>

<div class="container">
	<div class="row">
		<div class="col-lg-7 offset-lg-1">

			{% if success_message %}
			<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}

			<form class="create-form" method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.media }}
				{{ form | crispy }}
				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					{% if form.initial.image %}
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					{% endif %}
					<div class="middle">
						<div class="text">Change image</div>
						<div style="visibility: hidden">
							<input type="file" name="image" id="id_image_file" accept="image/*"
								onchange="readURL(this)">
						</div>
					</div>

				</div>


				{% for field in form %}
				<p>
					{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if form.non_field_errors %}
				<div style="color: red">
					<p>{{form.non_field_errors}}</p>
				</div>
				{% endif %}

				<!-- Submit btn -->
				<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">Update</button>
			</form>

			<!-- <div class="container">
				<div class="d-flex flex-column">
					{% if success_message %}
					<p class="m-auto">Changes to your post have been made successfully. <a href="{% url 'post' %}">Click here to view posts.</a></p>
					{% endif %}
				</div> -->
		</div>
	</div>
</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function (event) {
		document.getElementById('id_image_file').click();
	};

	function readURL(input) {
		var reader = new FileReader();
		reader.onload = function (e) {
			$('#id_image_display')
				.attr('src', e.target.result)
		};
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}