glamhubsite/artist/urls.py
from django.urls import path
from artist.views import (
    create_artistportfolio_view,
    detail_artistportfolio_view,
    edit_artistportfolio_view,
)

app_name = 'artist'

urlpatterns = [
    path('create/', create_artistportfolio_view, name="create"),
    path('<slug>/', detail_artistportfolio_view, name="detail"),
    path('<slug>/edit/', edit_artistportfolio_view, name="edit"),
]

glamhubsite/blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    comment_approve,
    comment_remove,
    add_comment_to_post,
)
# from personal.view import SearchResultsView

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
    path('posts/<int:pk>/comment/', add_comment_to_post, name='add_comment'), # noqa
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    # path('search/', SearchResultsView.as_view(), name='search_results'),
]

glamhubsite/glamhubsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

# from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views

from personal.views import (
    home_screen_view,
    about_us_view,
    blog_posts_view,
    artist_portfolio_screen,
    contact_us_view,
    services_screen_view,


    )

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)


from appointments.views import approve_appointment, reject_appointment

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('about/', about_us_view, name="about"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'), # noqa
    path('ckeditor/browser/', never_cache(login_required(views.browse)), name='ckeditor_browse'), # noqa
    path('posts/', blog_posts_view, name="post"),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),  # noqa
    path('register/', registration_view, name="register"),
    path('artist/', include('artist.urls', 'artist')),  # noqa
    path('artist_portfolios/', artist_portfolio_screen, name="artist_portfolios"), # noqa
    path('contact_us/', contact_us_view, name="contact_us"),
    path('services/', services_screen_view, name="services"),
    path('appointments/', include('appointments.urls')),
    path('reviews/', include('review.urls', 'reviews')),





    #  Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path(
        'password_reset/', auth_views.PasswordResetView.as_view(),
        name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),



    path(
        'appointment_approval/', approve_appointment),
    path(
        'appointment_reject/', reject_appointment),



]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # noqa
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # noqa

glamhubsite/personal/models.py
from django.db import models

# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class ContactUs(models.Model):
    message_name = models.CharField(max_length=255, null=False, blank=False)
    message = RichTextUploadingField(max_length=5000, null=False, blank=False)
    message_email = models.EmailField(max_length=70, blank=False, null=False)

glamhubsite/personal/views.py
from django.shortcuts import render, redirect, get_object_or_404
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.mail import send_mail


from blog.views import get_blog_queryset
from artist.views import get_artistportfolios_queryset  # noqa
from artist.models import ArtistPortfolio
from blog.forms import CommentForm
# from artist.forms import ContactUsForm
from blog.models import BlogPost


def home_screen_view(request):
    # context = {}

    # # to accept queries
    # query = ""
    # if request.GET:
    #     query = request.GET.get('q', '')
    #     context['query'] = str(query)

    # blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True) # noqa

    # # pagination for all website pages
    # page = request.GET.get('page', 1)
    # blog_posts_paginator = Paginator(blog_posts, BLOG_POST_PER_PAGE)

    # try:
    #     blog_posts = blog_posts_paginator.page(page)
    # except PageNotAnInteger:
    #     blog_posts = blog_posts_paginator.page(BLOG_POST_PER_PAGE)
    # except EmptyPage:
    #     blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

    # context['blog_posts'] = blog_posts
    return render(request, "personal/index.html")


def about_us_view(request):
    return render(request, "personal/about.html")


BLOG_POST_PER_PAGE = 5


def blog_posts_view(request, *args, **kwargs):
    context = {}

    # to accept queries
    # query = ""
    # if request.GET:
    #     query = request.GET.get('q', '')
    #     context['query'] = str(query)

    # blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)  # noqa

    query = ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)
    blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)
   

    # comments = blog_posts.comments.filter(active=True)
    # new_comment = None
    # # Comment posted
    # if request.method == "POST":
    #     comment_form = CommentForm(data=request.POST)
    #     if comment_form.is_valid():

    #         new_comment = comment_form.save(commit=False)
    #         new_comment.post = blog_posts
    #         new_comment.save()
    #     else:
    #         comment_form = CommentForm()

    # pagination for all website pages
    page = request.GET.get('page', 1)
    blog_posts_paginator = Paginator(blog_posts, BLOG_POST_PER_PAGE)

    try:
        blog_posts = blog_posts_paginator.page(page)
    except PageNotAnInteger:
        blog_posts = blog_posts_paginator.page(BLOG_POST_PER_PAGE)
    except EmptyPage:
        blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

    context['blog_posts'] = blog_posts

    return render(request, "personal/blog_posts.html", context)
    # return render(request, "personal/blog_posts.html", {"post": post, "comments": comments, "new_comment": new_comment, "comment_form": comment_form})


ARTISTPORTOFOLIOS_PER_PAGE = 5


def artist_portfolio_screen(request, *args, **kwargs):
    context = {}

    # to accept queries
    query = ""
    if request.GET:
        query = request.GET.get('q', '')
        context['query'] = str(query)

    # artistportfolios = sorted(get_artistportfolios_queryset(query), key=attrgetter('id'), reverse=True) # noqa
    artistportfolios = sorted(get_artistportfolios_queryset(query), key=attrgetter('business_name'), reverse=True)  # noqa
    context['artistportfolios'] = artistportfolios

    # pagination for all website pages
    page = request.GET.get('page', 1)
    artistportfolios_paginator = Paginator(artistportfolios, ARTISTPORTOFOLIOS_PER_PAGE)  # noqa

    try:
        artistportfolios = artistportfolios_paginator.page(page)
    except PageNotAnInteger:
        artistportfolios = artistportfolios_paginator.page(ARTISTPORTOFOLIOS_PER_PAGE)  # noqa
    except EmptyPage:
        artistportfolios = artistportfolios_paginator.page(artistportfolios_paginator.num_pages)  # noqa

    context['artistportfolios'] = artistportfolios

    return render(request, "personal/artist_portfolios.html", context)


def contact_us_view(request):

    if request.method == "POST":
        message_name = request.POST['message-name']
        message_email = request.POST['message-email']
        message = request.POST['message']

        # send an email
        send_mail(
            message_name,  # subject
            message,  # message
            message_email,  # from email
            ['glamhubsupport@gmail.com']  # to Email
        )

        return render(request, 'personal/contact_us.html', {'message_name': message_name})  # noqa
    else:
        return render(request, 'personal/contact_us.html', {})


def services_screen_view(request):

    return render(request, "personal/services.html", {})


# def SearchResultsView(request):
#     model = BlogPost
#     template_name = 'search_results.html'

glamhubsite/personal/templates/personal/artist_portfolios.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
	.container {
    max-width: 100%;
}
.element.style {
    width: 100%;
}
/* :: 11.0 Breadcrumb CSS */
.breadcrumb-content {
        position: relative;
        z-index: 1;
        text-align: center;
    }

    .breadcrumb-content h2 {
        font-size: 60px;
        margin-bottom: 15px;
    }

    @media only screen and (min-width: 992px) and (max-width: 1199px) {
        .breadcrumb-content h2 {
            font-size: 48px;
        }
    }

    @media only screen and (min-width: 768px) and (max-width: 991px) {
        .breadcrumb-content h2 {
            font-size: 48px;
        }
    }

    @media only screen and (max-width: 767px) {
        .breadcrumb-content h2 {
            font-size: 36px;
        }
    }

    .breadcrumb-content .breadcrumb {
        position: relative;
        padding: 0;
        background-color: transparent;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
    }

    .breadcrumb-content .breadcrumb .breadcrumb-item a:hover,
    .breadcrumb-content .breadcrumb .breadcrumb-item a:focus {
        color: #bca858;
    }

    .breadcrumb-content .breadcrumb .breadcrumb-item+.breadcrumb-item::before {
        content: '\f101';
        font-family: "FontAwesome";
    }
</style>

<!-- Breadcrumb Area Start -->
<section class="breadcrumb-area section-padding-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb-content">
                    <h2>What We Have</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="icon_house_alt"></i> Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Portfolios</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Area End -->


<!--Artist Portfolios section-->
<div class="container">
	<div class="row">

		<!-- portfolio feed -->
		<div class="left-column col-lg-7 offset-lg-1">

			<!-- Top 'create profolio' bar -->
			<div class="d-lg-none mb-3" >
				<div class="card m-auto d-flex flex-column p-3">
					<img class="img-fluid d-block m-auto pb-2" src="{% static 'glamhub logo.png' %}" width="72" height="72">
					<p class="lead">Get your business known?</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'artist:create' %}">Create Portfolio</a></p>
				</div>
			</div>
            <!-- end Top 'create profolio' bar -->

			<!-- artist profolios -->
			{% if artistportfolios %}
				{% for portfolio in artistportfolios %}
					<div class="artistportfolio-container">
						{% include 'artist/artistportfolio_snippet.html' with artistportfolio=portfolio %}
					</div>
				{% endfor %}
			{% else %}
                <div class="artistportfolio-container">
                    {% include 'artist/artistportfolio_snippet.html' with query=query %}
                </div>
			{% endif %}
            <!-- End Blog posts-->


            <!--Pagination-->
			{% include 'artist/artistportfolio_pagination.html' with artistportfolios=artistportfolios %}



		</div>
		<!-- end  portfolio feed -->

        <!-- Right 'create portforlio' column  -->
        {% if request.user.is_artist %}
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column" style="box-sizing: content-box;">

			<div class="card create-post-bar d-flex flex-column p-3" style="width: 120%;">
				<img class="img-fluid d-block m-auto pb-2"  src="{% static 'glamhub logo.png' %}" width="72" height="72">
                <p class="lead">Get your business known?</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'artist:create' %}">Create Portfolio</a></p>
			</div>

        </div>
        {% endif %}
		<!-- end Right 'create portfolio' column  -->

	</div>
</div>

{% endblock content %}

glamhubsite/personal/templates/personal/blog_posts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
    .container {
        max-width: 100%;

    }
    }



    /* :: 11.0 Breadcrumb CSS */
    .breadcrumb-content {
        position: relative;
        z-index: 1;
        text-align: center;
    }

    .breadcrumb-content h2 {
        font-size: 60px;
        margin-bottom: 15px;
    }

    @media only screen and (min-width: 992px) and (max-width: 1199px) {
        .breadcrumb-content h2 {
            font-size: 48px;
        }
    }

    @media only screen and (min-width: 768px) and (max-width: 991px) {
        .breadcrumb-content h2 {
            font-size: 48px;
        }
    }

    @media only screen and (max-width: 767px) {
        .breadcrumb-content h2 {
            font-size: 36px;
        }
    }

    .breadcrumb-content .breadcrumb {
        position: relative;
        padding: 0;
        background-color: transparent;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
    }

    .breadcrumb-content .breadcrumb .breadcrumb-item a:hover,
    .breadcrumb-content .breadcrumb .breadcrumb-item a:focus {
        color: #bca858;
    }

    .breadcrumb-content .breadcrumb .breadcrumb-item+.breadcrumb-item::before {
        content: '\f101';
        font-family: "FontAwesome";
    }
</style>

<!-- Breadcrumb Area Start -->
<section class="breadcrumb-area section-padding-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb-content" style="text-align: center;">
                    <h2>Our Blogs</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="icon_house_alt"></i>
                                    Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Blogs</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Area End -->

<!--blog posts section-->
<div class="container">
    <div class="row">

        <!-- blog feed -->
        <div class="left-column col-lg-7 offset-lg-1">

            <!-- Top 'create post' bar -->
            <div class="d-lg-none mb-3">
                <div class="card m-auto d-flex flex-column p-3">
                    <img class="img-fluid d-block m-auto pb-2" src="{% static 'glamhub logo.png' %}" width="72"
                        height="72">
                    <p class="lead">Having some exicitng facts or tutorials?</p>
                    <p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
                </div>
            </div>
            <!-- end Top 'create post' bar -->

            <!-- Blog posts-->
            {% if blog_posts %}
            {% for post in blog_posts %}
            <div class="blog-post-container">
                {% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
                
            </div>

            {% endfor %}
            {% else %}
            <div class="blog-post-container">
                {% include 'blog/snippets/blog_post_snippet.html' with query=query %}
            </div>
            {% endif %}
            <!-- End Blog posts-->

            <!--Pagination-->
            {% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}

        </div>
        <!-- end blog feed -->




        <!-- Right 'create post' column  -->
        <div class="right-column col-lg-3 d-lg-flex d-none flex-column">

            <div class="card create-post-bar d-flex flex-column p-3">
                <img class="img-fluid d-block m-auto pb-2" src="{% static 'glamhub logo.png' %}" width="72" height="72">
                <p class="lead">Having some exicitng facts or tutorials?</p>
                <p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create post</a></p>
            </div>

        </div>
        <!-- end Right 'create post' column  -->

    </div>
</div>

{% endblock content %}

glamhubsite/personal/templates/personal/contact_us.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
    * {
        margin: 0;
        padding: 0;
    }

    /*  Breadcrumb CSS */
    .breadcrumb-content {
        position: relative;
        z-index: 1;
        text-align: center;
    }

    .breadcrumb-content h2 {
        font-size: 60px;
        margin-bottom: 15px;
    }

    @media only screen and (min-width: 992px) and (max-width: 1199px) {
        .breadcrumb-content h2 {
            font-size: 48px;
        }
    }

    @media only screen and (min-width: 768px) and (max-width: 991px) {
        .breadcrumb-content h2 {
            font-size: 48px;
        }
    }

    @media only screen and (max-width: 767px) {
        .breadcrumb-content h2 {
            font-size: 36px;
        }
    }

    .breadcrumb-content .breadcrumb {
        position: relative;
        padding: 0;
        background-color: transparent;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        justify-content: center;
    }

    .breadcrumb-content .breadcrumb .breadcrumb-item a:hover,
    .breadcrumb-content .breadcrumb .breadcrumb-item a:focus {
        color: #bca858;
    }

    .breadcrumb-content .breadcrumb .breadcrumb-item+.breadcrumb-item::before {
        content: '\f101';
        font-family: "FontAwesome";
    }

    /*  google maps area */
    .google-maps-area {
        position: relative;
        z-index: 1;
        height: 400px;
    }

    @media only screen and (max-width: 767px) {
        .google-maps-area {
            height: 320px;
        }
    }

    .google-maps-area iframe {
        width: 100%;
        height: 100%;
        border: none;
    }

    /*  Contact form */

    .contact-form {
        position: relative;
        z-index: 1;
        border: 1px solid #e5e5e5;
        padding: 30px;
    }

    @media only screen and (max-width: 767px) {
    .contact-form {
            padding: 20px;
        }
    }

    @media only screen and (max-width: 767px) {
    .contact-form h2 {
            font-size: 24px;
        }
    }

    @media only screen and (max-width: 767px) {
    .contact-form h4 {
            font-size: 20px;
        }
    }

    .contact-form .form-control {
        width: 100%;
        height: 50px;
        padding: 0 20px;
        border-radius: 2px;
        color: #acacac;
        font-size: 14px;
    }

    .contact-form .form-control:focus {
        box-shadow: none;
        border-color: #bca858;
    }

    .contact-form textarea.form-control {
        height: 150px;
        padding: 20px;
    }

    .single-contact-information {
        position: relative;
        z-index: 1;
        text-align: center;
    }

    .single-contact-information i {
        font-size: 30px;
        margin-bottom: 15px;
        color: #bca858;
        display: block;
    }

    .single-contact-information h4 {
        display: block;
        margin-bottom: 15px;
    }

    .single-contact-information p {
        margin-bottom: 0;
    }

    body {
        font-family: "Montserrat", sans-serif;
        font-weight: 400;
        font-size: 14px;
    }

    .contact-us {
        position: relative;
        z-index: 1;
    }

    .contact-us .google-maps {
        position: relative;
        z-index: 1;
        width: 100%;
        height: 470px;
    }

    @media only screen and (max-width: 767px) {
        .contact-us .google-maps {
            height: 280px;
        }
    }

    .contact-us .google-maps iframe {
        width: 100%;
        height: 100%;
        border: none;
    }

    .contact-information {
        position: relative;
        z-index: 1;
        padding: 30px 50px;
        background-color: #00aeef;
        border-radius: 3px;
    }

    @media only screen and (max-width: 767px) {
        .contact-information {
            margin-bottom: 100px;
        }
    }

    .contact-information h5 {
        color: #ffffff;
    }

    .contact-information p {
        color: #ffffff;
    }



    .contact-form {
        position: relative;
        z-index: 1;
    }

    .contact-form .form-control {
        width: 100%;
        height: 46px;
        padding: 0 15px;
        font-size: 13px;
        font-style: italic;
    }

    .contact-form .form-control:focus {
        box-shadow: none;
        border-color: #00aeef;
    }

    .contact-form textarea.form-control {
        height: 110px;
        padding: 15px;
    }
</style>


<!-- Breadcrumb Area Start -->
<section class="breadcrumb-area section-padding-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb-content">
                    <h2>Our Contacts</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home' %}"><i class="icon_house_alt"></i>
                                    Home</a>
                            </li>
                            <li class="breadcrumb-item active" aria-current="page">Contact us</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Area End -->

<!--What to display if an email is sent-->
{%if message_name %}
    <center>
        <h2> Thanks {{ message_name}}</h2>
        <p>We received your email and we will respond shortly...</p>
    </center>
    <br><br>

{% else %}
<!-- Google Maps -->
<div class="google-maps-area">
    <iframe
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.8031387053393!2d36.78656074930154!3d-1.292534535990444!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x182f10a39343ae3b%3A0x14355e986ccd2ce7!2slandmark%20plaza!5e0!3m2!1sen!2ske!4v1595962247750!5m2!1sen!2ske"
        allowfullscreen=""></iframe>
</div>
<!-- Google Maps End -->

<!-- Contact Information Area  -->
<section class="contact-information-area section-padding-80-0" >
    <div class="container">
        <div class="row">
            <!-- Single Contact Information -->
            <div class="col-12 col-sm-6 col-lg-3">
                <div class="single-contact-information mb-80">
                    <i class="icon_phone"></i>
                    <h4>Phone</h4>
                    <p>+254 210 926 122</p>
                </div>
            </div>

            <!-- Single Contact Information -->
            <div class="col-12 col-sm-6 col-lg-3">
                <div class="single-contact-information mb-80">
                    <i class="icon_pin"></i>
                    <h4>Address</h4>
                    <p>28 Landmark Plaza, Argwings Kodhek Rd, Nairobi</p>
                </div>
            </div>

            <!-- Single Contact Information -->
            <div class="col-12 col-sm-6 col-lg-3">
                <div class="single-contact-information mb-80">
                    <i class="icon_mail"></i>
                    <h4>Email</h4>
                    <p>info.glamhub@gmail.com</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Contact Information Area End -->

<!-- Contact Area Start -->
<section class="contact-area section-padding-80 mt-5 pt-5"
style="background-color: #efefef;">
    <div class="container">
        <div class="row">
            <!-- Section Heading -->
            <div class="col-12">
                <div class="section-heading text-center">
                    <h2>Leave message</h2>
                    <p>Our staff will get back  to you later and answer your questions.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <!-- Form -->
                <form action="#" method="post" class="contact-form border-0 p-0 w-100">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-lg-6">
                            <input type="text" name="message-name" class="form-control mb-30" placeholder="Your Name">
                        </div>
                        <div class="col-lg-6">
                            <input type="email" name="message-email" class="form-control mb-30" placeholder="Email">
                        </div>
                        <div class="col-12 pt-4">
                            <textarea name="message" class="form-control mb-30"
                                placeholder="Send us an email..."></textarea>
                        </div>
                        <div class="col-12 text-center pt-4">
                            <button type="submit" class="btn btn btn-3 mt-15 active btn-primary">Send Message</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
{% endif %}

<!-- Contact Area End -->


{% endblock content %}

glamhubsite/personal/templates/personal/searchbar.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{{ error }}

{% if post %}
  <center><h4>Search Results Found</h4></center>
  <br>


  {% for i in post %}
  <center><h5><a href="/posts/{{i.slug}}">{{i.title}}:{{i.body}}</a></h5></center>
  {% endfor %}

{% else %}
  <center><h4>Sorry nothing found...</h4></center>
{% endfor %}
{% endblock content %}