glamhubsite/appointments/urls.py
from django.urls import path

from . import views

app_name = 'appointments'
urlpatterns = [
    path('<str:slug>/create/', views.AppointmentCreateView.as_view(), name='create'), # noqa
    path('<str:slug>/list/', views.list_appointments, name='list'), # noqa
    path('<int:pk>/approve/', views.approve_appointment, name='approve'), # noqa
    path('<int:pk>/reject/', views.reject_appointment, name='reject'), # noqa




]

glamhubsite/blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    comment_approve,
    comment_remove,
    add_comment_to_post,
)
# from personal.view import SearchResultsView

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit/', edit_blog_view, name="edit"),
    path('posts/<int:pk>/comment/', add_comment_to_post, name='add_comment'), # noqa
    path('comment/<int:pk>/approve/', comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', comment_remove, name='comment_remove'),
    # path('search/', SearchResultsView.as_view(), name='search_results'),
]

glamhubsite/glamhubsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

# from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from ckeditor_uploader import views

from personal.views import (
    home_screen_view,
    about_us_view,
    blog_posts_view,
    artist_portfolio_screen,
    contact_us_view,
    services_screen_view,


    )

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)


from appointments.views import approve_appointment, reject_appointment

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('about/', about_us_view, name="about"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    path('ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'), # noqa
    path('ckeditor/browser/', never_cache(login_required(views.browse)), name='ckeditor_browse'), # noqa
    path('posts/', blog_posts_view, name="post"),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),  # noqa
    path('register/', registration_view, name="register"),
    path('artist/', include('artist.urls', 'artist')),  # noqa
    path('artist_portfolios/', artist_portfolio_screen, name="artist_portfolios"), # noqa
    path('contact_us/', contact_us_view, name="contact_us"),
    path('services/', services_screen_view, name="services"),
    path('appointments/', include('appointments.urls')),
    path('reviews/', include('review.urls', 'reviews')),





    #  Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='registration/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_done.html'),
        name='password_reset_done'),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm'),
    path(
        'password_reset/', auth_views.PasswordResetView.as_view(),
        name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'),
        name='password_reset_complete'),



    path(
        'appointment_approval/', approve_appointment),
    path(
        'appointment_reject/', reject_appointment),



]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)  # noqa
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # noqa

glamhubsite/appointments/models.py
from django.db import models

from account.models import Account
from artist.models import ArtistPortfolio


class Appointment(models.Model):
    artist = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name='artist')
    client = models.ForeignKey(
        Account, on_delete=models.CASCADE, related_name='client',
        blank=True, null=True)
    portfolio = models.ForeignKey(
        ArtistPortfolio, on_delete=models.CASCADE,
        blank=True, null=True)
    appointment_date = models.DateField()
    description = models.TextField(blank=False, null=False, max_length=200,)
    is_approved = models.BooleanField(blank=True, null=True)

    class Meta:
        unique_together = ('artist', 'appointment_date')

glamhubsite/appointments/forms.py
from django import forms

from .models import Appointment


class AppointmentForm(forms.ModelForm):
    # appointment_date = forms.DateField(
    #     widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    appointment_date = forms.DateField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Appointment
        fields = ('appointment_date', 'description')

glamhubsite/appointments/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
# from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from artist.models import ArtistPortfolio
from account.models import Account
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect

from .forms import AppointmentForm
from .models import Appointment


class AppointmentCreateView(LoginRequiredMixin, View):
    template_name = 'appointments/appointment_create.html'
    form_class = AppointmentForm

    def get(self, request, *args, **kwargs):
        portfolio = get_object_or_404(ArtistPortfolio, slug=kwargs['slug'])
        booked_dates = Appointment.objects.filter(
            artist=portfolio.business_owner, is_approved=True).order_by(
                'appointment_date').values_list('appointment_date', flat=True)
        blocked_dates = [date.strftime('%d/%m/%Y') for date in booked_dates]
        form = self.form_class(
            initial={
                'artist': portfolio.business_owner,
                'portfolio': portfolio
            }
        )
        context = {
            'blocked_dates': blocked_dates,
            'form': form
        }
        return render(request, self.template_name, context=context)

    def post(self, request, *args, **kwargs):
        portfolio = get_object_or_404(ArtistPortfolio, slug=kwargs['slug'])
        form = self.form_class(request.POST)
        if form.is_valid():
            try:
                appointment = form.save(commit=False)
                appointment.artist = portfolio.business_owner
                appointment.portfolio = portfolio
                appointment.client = request.user
                appointment.save()

                messages.success(request, "Appointment created successfully. An email will be sent to you once your submission is reviewed ")
                url = reverse_lazy('artist:detail', kwargs={
                                   'slug': portfolio.slug})
                return redirect(url)
            except Exception:
                messages.error(
                    request, "Appointment was not updated. Please try again.")
                form = self.form_class(
                    initial={
                        'artist': portfolio.business_owner,
                        'portfolio': portfolio,
                        'appointment_date': appointment.appointment_date,
                        'description': appointment.description
                    }
                )
                # return render(request, 'appointments/appointment_create.html', context)
                return render(request, self.template_name, {'form': form})
        # return render(request, 'appointments/appointment_create.html', context)
        return render(request, self.template_name, {'form': form})


@login_required()
def list_appointments(request, slug):
    template_name = 'appointments/appointment_list.html'
    queryset = Appointment.objects.filter(
        portfolio__slug=slug, artist=request.user).order_by('-appointment_date')
    return render(request, template_name, {'appointments': queryset})


@login_required()
def approve_appointment(request, pk):
    appointment = get_object_or_404(Appointment, pk=pk)
    if appointment.artist == request.user:
        print("approving")
        appointment.is_approved = True
        appointment.save()
        messages.success(request, "Appointment approved. An email will be sent to the client")
       #  send email to appointment.client.email
        subject = 'Appointment Feedback'
        message = None
        from_email = 'glamhubsite.com'
        html_message = render_to_string(
            'feedback/appointment_approval_email.html',
            context={
                'client': appointment.client.username,
                'business_name': appointment.portfolio.business_name,
                'description': appointment.description,
                'appointment_date': appointment.appointment_date
            }
        )
        try:
            send_mail(
                subject, message, from_email,
                [appointment.client.email, request.user.email],
                html_message=html_message)
        except Exception:
            pass
        url = reverse_lazy(
            'appointments:list',
            kwargs={'slug': appointment.portfolio.slug}
        )
        return redirect(url)
    else:
        return redirect(request.get_full_path())


@login_required()
def reject_appointment(request, pk):
    appointment = get_object_or_404(Appointment, pk=pk)
    if appointment.artist == request.user:
        print("rejecting")
        appointment.is_approved = False
        appointment.save()
        messages.error(request, "Appointment rejected. An email will be sent to the client")
       #  send email to appointment.client.email
        subject = 'Appointment Feedback'
        message = None
        from_email = 'glamhubsite.com'
        html_message = render_to_string(
            'feedback/appointment_rejection_email.html',
            context={
                'client': appointment.client.username,
                'business_name': appointment.portfolio.business_name,
                'description': appointment.description,
                'appointment_date': appointment.appointment_date

            }
        )
        try:
            send_mail(
                subject, message, from_email,
                [appointment.client.email, request.user.email],
                html_message=html_message)
        except Exception:
            pass
        url = reverse_lazy(
            'appointments:list',
            kwargs={'slug': appointment.portfolio.slug}
        )
        return redirect(url)
    else:
        return redirect(request.get_full_path())

glamhubsite/appointments/templates/appointments/appointment_create.html
{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block page_name %}
Create Appointment
{% endblock %}


{% block content %}
<style type="text/css">
    .card {
        max-width: 800px;
    }


    .container {
        padding: 20px;
    }


    .btn {
        border-radius: 2px;
        color: #343b40;
        border-color: #343b40;
        background: rgb(16, 245, 233);
        ;
        outline: none;
    }

    .btn:hover,
    .btn:focus {
        border-color: rgb(16, 245, 233);
        ;
        background-color: #343b40;
        color: rgb(16, 245, 233);
        ;
    }

    .datepicker-here {
        box-sizing: border-box;
        width: 70%;
        margin: auto;
        border: 3px solid rgb(16, 245, 233);
        padding-right: 20px;
        padding-left: 30px;
        padding-bottom: 20px;
        padding-top: 20px;

    }
</style>

<div class="container">
    <div class="row">
        <div class="card m-auto"
            style="background-color:#343b40; text-align: center; color: rgb(247, 244, 244); width: 40%;">
            <form method="POST" action="{% url 'appointments:create' form.initial.portfolio.slug %}">
                {% csrf_token %}
                {{ form | crispy }}
                <!-- <h5 style="text-align: center; font-family:Georgia, 'Times New Roman', Times, serif;">The Date</h5>
                <div class="datepicker-here" data-language='en' style="align-items: center;"></div>
                <div>
                    <hr>
                    <h5 style="text-align: center; font-family:Georgia, 'Times New Roman', Times, serif;">Description
                    </h5>
                    <textarea placeholder="What do you want done?" cols="40" rows="6"></textarea>
                </div> -->

                <div> <button type="submit" class="btn btn-primary">Submit</button></div>

            </form>
        </div>

    </div>

</div>

<script>
    setDatePicker({{ blocked_dates| safe}})
</script>
{% endblock %}

glamhubsite/appointments/templates/appointments/appointment_edit.html
{% extends 'common/base.html' %}

{% load static %}

{% block page_css %}
<link rel="stylesheet" type="text/css" href="{% static 'appointments/css/appointments.css' %}">
{% endblock %}

{% block page_js %}
<script src="{% static 'appointments/js/appointments.js' %}"></script>
{% endblock %}

{% block page_name %}
Edit Appointment
{% endblock %}

{% block content %}

{% endblock %}

glamhubsite/appointments/templates/appointments/appointment_list.html
{% extends 'base.html' %}

{% load static %}

{% block page_name %}
My Appointments
{% endblock %}

{% block content %}

<style type="text/css">
	.card {
		max-width: 800px;
	}


	.container {
		padding: 20px;
	}


	/* .btn {
		border-radius: 2px;
		color: #343b40;
		border-color: #343b40;
		background: rgb(16, 245, 233);
		;
		outline: none;
	}

	.btn:hover,
	.btn:focus {
		border-color: rgb(16, 245, 233);
		;
		background-color: #343b40;
		color: rgb(16, 245, 233);
		;
	} */

	table {
		table-layout: fixed;
		width: 100%;
	}

	table,
	td,
	th {
		table-layout: fixed;
		border: 1px solid black;


	}

	th {
		background-color: #343b40;
		color: white;
		padding: 5px;
		text-align: center;
	}

	td {
		text-align: center;
	}
</style>


{% if appointments%}
{% for appointment in appointments %}
<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<table>
					<tr>
						<th> Date</th>
						<th>Description</th>
						<th>Client</th>
						<th colspan="2" >Action</th>
						<th>Status</th>
					</tr>
					<tr>
						<td>{{appointment.appointment_date}}</td>
						<td>{{appointment.description}}</td>
						<td>{{appointment.client.username}}</td>
						<td colspan="2">
							<a
								href="{%url 'appointments:approve' appointment.pk %}"
								class="btn btn-outline-success {% if appointment.is_approved is True %} disabled {% endif %}"
								{% if appointment.is_approved is True %} aria-disabled="true" {% endif %}
							>Approve</a>
							<a
								href="{%url 'appointments:reject' appointment.pk %}"
								class="btn btn-outline-warning {% if appointment.is_approved is False %} disabled {% endif %}"
								{% if appointment.is_approved is False %} aria-disabled="true" {% endif %}
							>Reject</a>
						</td>
						<td>
							{% if appointment.is_approved is True %}
								<p>Approved</p>
							{% elif appointment.is_approved is False %}
								<p>Rejected</p>
							{% else %}
								<p>Not yet confirmed</p>
							{% endif %}
						</td>
					</tr>
				</table>


			</div>
		</div>
	</div>








</div>
{% endfor %}
{% else %}
<div class="container">
	<div class="row">
		<div class="card m-auto">
			<div class="card-body mt-2 mb-2">
				<h2 class="card-title" style="text-align: center;">Nothing Found</h2>
				<!-- <p class="card-text">There were no results matching the search: "{{query}}"</p> -->
			</div>
		</div>
	</div>
</div>

{% endif %}

{% endblock %}